import Bubble from "@comp/Bubble";
import Choices from "@comp/Choices";
import Container from "@comp/Container";
import Feedback from "@comp/Feedback";
import InputBubble from "@comp/InputBubble";
import Footer from "@comp/Layout/Footer";
import Header from "@comp/Layout/Header";
import LoadingBubble from "@comp/LoadingBubble";
import { useLang } from "@hooks/useLang";
import { common } from "@locales/common";
import MessageBubbles from "@style/indexPage.css";
import Head from "next/head";
import type { SyntheticEvent } from "react";
import { useEffect, useRef, useState } from "react";

export default function Home(): JSX.Element {
  const lang = useLang();
  const chatEl = useRef<HTMLInputElement>(null);
  const suggestEl = useRef<HTMLDivElement>(null);
  const [replies, setReplies] = useState([
    { id: 0, type: "comp", message: common[lang].greet },
    { id: 2, type: "comp", message: common[lang].helperTwo },
    { id: 3, type: "comp", message: common[lang].suggestion },
  ]);
  const [text, setText] = useState("");
  const [feedback, setFeedback] = useState(false);
  const [loading, setLoading] = useState(false);
  const [input, setInput] = useState(true);
  const [reset, setReset] = useState(false);
  const [visited, setVisited] = useState(false);
  const [suggestion, setSuggestion] = useState<any[]>([]);
  const initialMessage = { id: 0, type: "bot", games: null, message: common[lang].greet };
  const [messages, setMessages] = useState([initialMessage]);

  useEffect(() => {
    if (chatEl?.current) {
      chatEl.current.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }
  }, [messages]);
  useEffect(() => {
    if (suggestEl?.current) {
      suggestEl.current.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }
  }, [suggestion]);
  useEffect(() => {
    if (typeof window !== "undefined") {
      if (localStorage.getItem("visited")) {
        setVisited(true);
      } else {
        localStorage.setItem("visited", "true");
      }
    }
  }, []);

  const handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    setLoading(true);
    const obj = { id: messages.length + 2, type: "user", games: null, message: text };
    setMessages((messages) => messages.concat(obj));
    // setReplies([...replies, obj]);
    await getData(text);
  };
  const handleReset = async (): Promise<void> => {
    setLoading(true);
  };
  const handleChoice = async (e: SyntheticEvent) => {
    e.preventDefault();
    switch (e.currentTarget.id) {
      case "good": {
        setFeedback(false);
        setReset(true);
        break;
      }
      case "bad": {
        setFeedback(false);
        setSuggestion([]);
        setInput(true);
        break;
      }
      case "reset": {
        setReset(false);
        setInput(true);
        setMessages([initialMessage]);
        break;
      }
    }
  };
  const getData = async (query: string) => {
    try {
      setInput(false);
      setLoading(true);

      const response = await fetch(`/api/search?question=${query}`);
      if (response.status !== 200 && response.status !== 504) {
        const errorMsg = { id: messages.length + 5, type: "error", games: null, message: "Oops, something went wrong" };
        // filtering out any previous error messages to avoid confusion
        setMessages((messages) => messages.concat(errorMsg));
        setLoading(false);
      }
      const { data } = await response.json();
      if (data.length > 0) {
        setSuggestion(data);
        const gamesAddition = {
          id: messages.length + 3,
          type: "suggestion",
          games: data,
          message: "Here are some games fitting that description",
        };
        setMessages((messages) => messages.concat(gamesAddition));
        setFeedback(true);
        setLoading(false);
        setReset(true);
      }
      if (data.length === 0) {
        setReset(true);
        setLoading(false);
      }

      // Useful for local testing
      // const response = await fetch("./placeholder.json");
      // const data = await response.json();
      // const setVariables = () => {
      //   setFeedback(true);
      //   setSuggestion(data.results);
      // };
      // setTimeout(setVariables, 2000);
    } catch {
      setReset(true);
    }
  };

  return (
    <>
      <Head>
        <title>{common[lang].title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title={common[lang].title} />

      <Container visited={visited}>
        <div className={MessageBubbles}> {messages && messages.map((msg) => <Bubble key={msg.id} {...msg} />)} </div>

        {loading && <LoadingBubble />}

        {input && (
          <InputBubble ref={chatEl} text={text} setText={setText} handleSubmit={handleSubmit} visited={visited} />
        )}

        {reset && (
          <Feedback ref={suggestEl}>
            <Choices
              variant="reset"
              onClick={async (e) => {
                await handleChoice(e);
              }}
            />
          </Feedback>
        )}
      </Container>

      <Footer />
    </>
  );
}
